# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadconvert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_slug',
            field=models.SlugField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='movie',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
