# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import uploadconvert.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadconvert', '0002_auto_20160429_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(upload_to=uploadconvert.models.path_and_rename),
        ),
    ]
