# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadconvert', '0003_auto_20160429_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='title_slug',
        ),
    ]
