# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadconvert', '0004_remove_movie_title_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_slug',
            field=models.CharField(default=b'', max_length=110, verbose_name='none'),
        ),
    ]
